Brain loading
Klepac-Ceraj-Lab/Resonance pull request #115
Opened 2023-02-20 19:47 UTC by Hugemiler

Minor changes to Brain stuff that were left out of fig3-4 PR

2023-02-20 19:47 UTC, Hugemiler commented
@kescobo can you please take a look at those minor changes to source?

2023-02-20 20:20 UTC, kescobo requested changes

2023-02-20 20:20 UTC, kescobo commented on src/microbiomejl_interface.jl
>  function comm2wide(cmp::CommunityProfile; feature_filter=identity, sample_filter=identity)
```suggestion
function comm2wide(cmp::CommunityProfile; feature_filter=identity, sample_filter=identity, feature_funct=name)
```

2023-02-20 20:20 UTC, kescobo commented on src/microbiomejl_interface.jl
> +
```suggestion
        return hcat(md, DataFrame(collect(abundances(cmp)'), feature_func.(features(cmp)), makeunique=true))
```

2023-02-26 18:56 UTC, kescobo approved these changes

2023-02-26 19:14 UTC, merged