Added Resonance.load(::Neuroimaging) to load_data.jl and Brain.jl
Klepac-Ceraj-Lab/Resonance pull request #64
Opened 2022-08-12 21:01 UTC by Hugemiler

Please review the addition of `Resonance.load(::Neuroimaging)` to the data loading scripts. Function works locally.

2022-08-13 01:41 UTC, kescobo requested changes

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +        df."Left-Thalamus" = df."Left-Thalamus" .+ df."Left-Thalamus-Proper"
Can we just add a couple of gut-checks here? Something like 

```
all(row-> row."Left-Thalamus" == 0 ⊻ row."Left-Thalamus-Proper", eachrow(df)) || error()
```

for each pair.

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +end # end function
See `split_tp()` function in `wrangle.jl`: https://github.com/Klepac-Ceraj-Lab/Resonance/blob/main/src/wrangle.jl#L1-L11

Can just do `split_tp.(stringsvector)`

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +        df."Left-Thalamus" = df."Left-Thalamus" .+ df."Left-Thalamus-Proper"
Also, why is this line indented?

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +        df."Left-Thalamus" = df."Left-Thalamus" .+ df."Left-Thalamus-Proper"
```suggestion
        df."Left-Thalamus"  .+= df."Left-Thalamus-Proper"
```

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +        df."IntraCranialVol" = df."EstimatedTotalIntraCranialVol" .+ df."IntraCranialVol"
```suggestion
        df."Right-Thalamus"  .+= df."Right-Thalamus-Proper"
        df."IntraCranialVol" .+= df."IntraCranialVol"
```

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +    subjs, tpts = split_subject_timepoint(df."Measure:volume")
```suggestion
    stps = DataFrame(split_tp.(df."Measure:volume"))
```

Because a vector of NTs satisties Tables.jl interface

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +    df = hcat(DataFrame(:subject => subjs, :timepoint => tpts ), select(df, _reduced_braincols))
```suggestion
    df = hcat(stps, select(df, _reduced_braincols))
```

2022-08-13 01:41 UTC, kescobo commented on src/data_loading.jl
> +    return sort(df, [:subject, :timepoint])
```suggestion
    return sort!(df, [:subject, :timepoint])
```
No need to make a copy

2022-08-16 15:37 UTC, Hugemiler commented
Your comments were resolved. Please review and approve.

2022-08-16 15:38 UTC, Hugemiler reviewed
All resolved.

2022-08-16 15:51 UTC, kescobo approved these changes

2022-08-16 15:51 UTC, merged